Updates for pkg target.
M    OSX_Resources/InstallationCheck
M    OSX_Resources/Info.plist
M    OSX_Resources/InstallationCheck.strings
M    OSX_Resources/Description.plist
M    Makefile.am

diff --git a/OSX_Resources/InstallationCheck b/OSX_Resources/InstallationCheck
--- a/OSX_Resources/InstallationCheck
+++ b/OSX_Resources/InstallationCheck
@@ -1,5 +1,21 @@
 #!/bin/sh
 #
+# Check CPU type
+
+architecture="i386" 
+
+if arch | grep -v "$architecture"
+then
+    if arch | grep "i386"
+    then
+	# You have an intel mac error message
+	exit 115
+    else
+	# PowerPC message
+	exit 116
+    fi
+fi
+
 # Check to make sure the computer is running 10.3 or later.
 
 version=`uname -a | sed 's/.*Darwin Kernel Version \([0-9.]*\):.*/\1/'`
@@ -17,7 +33,7 @@ fi
 
 if test -z "`dap-config --version 2> /dev/null`"
 then
-    # fail and display message 113-32 (81)
+    # fail and display message 113-96 (17)
     exit 113
 fi
 
